version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq_container'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  shipping-service:
    image: aluth313/shipping-service:v1
    container_name: 'shipping_service'
    ports:
        - 3001:3001
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node ../shipping-service/index.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
  order-service:
    image: aluth313/order-service:v1
    container_name: 'order_service'
    ports:
        - 3000:3000
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node ../order-service/index.js'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
  rabbitmq_log:
networks:
  rabbitmq_network:
    driver: bridge