version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq_container'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - rabbitmq_network
volumes:
  rabbitmq_data:
  rabbitmq_log:
networks:
  rabbitmq_network:
    driver: bridge